const mockData = [
  { id: 0, type:"카시트", title: "[순성] 데일리모노 ISOFIX_카시트", desc: "신생아~7세까지 사용가능", image: "img/daily_mono.png",imageitem:"img/daily_mono_item.jpg", options: [ { optionType: "색상선택", optionValues: ["모노블랙"],},], weight:"8.5kg",cost:"390,000원",sale:"298,000원", details:"img/daily_mono_details.jpg" },
  { id: 1, type:"카시트", title: "[다이치] 듀얼 오가닉 Larch-Fix 카시트", desc: "신생아~5세까지 사용가능", image: "img/daichi_1.png", options: [ { optionType: "색상선택", optionValues: ["오가니차콜"],},], weight:"6kg", cost:"300,000원",sale:"176,000원", details:"img/daichi_1_details.jpg"  },
  { id: 2, type:"카시트", title: "[루미] 스펙트 I_ 360회전카시트", desc: "신생아~7세까지 사용가능", image: "img/spect.png", options: [ { optionType: "색상선택", optionValues: ["블랙","핑크","그레이"],},], weight:"15kg", cost:"840,000원",sale:"378,000원", details:"img/spect_details.jpg"},
  { id: 3, type:"카시트", title: "[순성] 듀클핀 Isofix_카시트", desc: "신생아~7세까지 사용가능", image: "img/duklefin.png",options: [ { optionType: "색상선택", optionValues: ["애쉬블루","아이언그레이","그레이","네이비","탠저린","더블랙"],},], weight:"14.6kg",cost:"700,000원",sale:"347,000원", details:"img/duklefin_details.jpg" },
  { id: 4, type:"카시트", title: "[다이치] 원픽스 360 Isofix 카시트", desc: "신생아~4세까지 사용가능", image: "img/daichi_one.png",options: [ { optionType: "색상선택", optionValues: ["블랙","다크그레이","베이지"],},], weight:"13.42kg",cost:"780,000원",sale:"368,000원", details:"img/daichi_one_details.jpg" },
  { id: 5, title: "[순성]듀클캐리", desc: "3~8세까지 사용가능", image: "img/dukle_carry.png", options: [ { optionType: "색상선택", optionValues: ["그레이"],},], weight:"3.3kg",cost:"200,000원",sale:"92,000원", details:"img/dukle_carry_details.jpg" },
  { id: 6, type:"유모차", title: "[미고] 미니플러스5유모차", desc: "신생아~3세까지 사용가능", image: "img/migo.png" ,options: [ { optionType: "색상선택", optionValues: ["멜란지그레이"],},], weight:"5.8kg"},
  { id: 7, type:"유모차", title: "[지비] 마리스2유모차", desc: "신생아~4세까지 사용가능", image: "img/jibby_maris.png",options: [ { optionType: "색상선택", optionValues: ["럭스블랙","실버폭그레이","체리레드"],},], weightused:"~17kg",cost:"980,000원",sale:"230,000원", details:"img/djibby_maris_details.jpg"  },
  { id: 8, type:"유모차", title: "[리안]21.그램플러스유모차", desc: "신생아~36개월까지 사용가능", image: "img/lian_gram plus.png" ,options: [ { optionType: "색상선택", optionValues: ["시크블랙","크림아이보리","프렌치블루"],},], weight:"5.8kg",cost:"	328,000원",sale:"208,000원", details:"img/lian_gram_plus_details.jpg"  },
  { id: 9, type:"유모차", title: "[리안]트윈쌍둥이절충형", desc: "신생아~36개월까지 사용가능", image: "img/lian_twin.png",options: [ { optionType: "색상선택", optionValues: ["미스틱네이비","슬레이트그레이"],},], weight:"7.7kg",cost:"	568,000원",sale:"282,000원", details:"img/lian_twin_details.jpg" },
  { id: 10, type:"유모차", title: "[조이]애발라이트듀오유모차", desc: "신생아~15kg까지 사용가능", image: "img/joy_avalite.png",options: [ { optionType: "색상선택", optionValues: ["코알(블랙)","딥씨(네이비)"],},], weight:"10.32kg",cost:"	570,000원",sale:"328,000원", details:"img/joy_avalite_details.jpg" },
  { id: 11, type:"범퍼매트", title: "[조아뜨]듀얼범퍼매트_T500", desc: "주문제작상품", image: "img/joaht.png",options: [ { optionType: "색상선택", optionValues: ["그레이","크림"],},], cost:"	485,000원",sale:"223,000원", details:"img/joaht_details.jpg" },
  { id: 12, type:"아기띠",title: "[미고]올인원 힙시트", desc: "신생아~36개월까지 사용가능", image: "img/mi_go_hip sheet.png",options: [ { optionType: "색상선택", optionValues: ["그레이"],},], weightused:"3.5kg~15kg" },
  { id: 13, type:"아기띠", title: "[포그내]맥스라이트", desc: "신생아~36개월까지 사용가능", image: "img/following max light.png",options: [ { optionType: "색상선택", optionValues: ["데님베이지", "데님그레이"],},], material:" 겉감-나일론 100%,폴리에스터 100%",cost:"320,000원",sale:"228,000원", details:"img/following max_details.jpg"},
  { id: 14, title: "[다이치]루이3in1올인원아기띠", desc: "신생아~36개월까지 사용가능", image: "img/dich_louis.png", options: [ { optionType: "색상선택", optionValues: ["차콜",],},], cost:"280,000원",sale:"145,000원", details:"img/dich_louis_details.jpg"},
  { id: 15, title: "[유팡]플러스LED젖병소독기", desc: "자동모드,터보모드", image: "img/yooppang plus.png",options: [ { optionType: "색상선택", optionValues: ["화이트", "블루","그레이","오렌지","그린","베이직"],},], function:"자동모드, 터보모드",weight:"6.54kg",cost:"	297,000원",sale:"235,000원", details:"img/yooppang plus_details.jpg" },
  { id: 16, title: "[레이퀸]6세대젖병소독기", desc: "완벽한 살균건조", image: "img/ray queen.png",options: [ { optionType: "색상선택", optionValues: ["그레이", "화이트","핑크"],},], function:"완벽한살균건조, 상하uv자외선",weight:"5.5kg",cost:"	300,000원",sale:"182,000원", details:"img/ray queen_details.jpg" },
  { id: 17, type:"젖병소독기", title: "[스펙트라]젖병소독기", desc: "간편한 원터치조작", image: "img/spectra.png",options: [ { optionType: "색상선택", optionValues: ["클래시화이트", "차밍다크그레이"],},], function:"완벽한 살균건조, 듀얼UV자외선",weight:"5.5kg",cost:"218,000원",sale:"185,000원", details:"img/spectra_details.jpg" },
  { id: 18, type:"디럭스유모차", title: "[베베프람]이지고웨건플러스", desc: "권장하중 50kg까지", image: "img/bebe pram.png",options: [ { optionType: "색상선택", optionValues: ["그레이"],},], weight:"14.5kg", weightused:"50kg",cost:"260,000원",sale:"167,000원", details:"img/bebe pram_details.jpg"  },

];

export default mockData;
